general:
  prefixs: ["."]
  embed_color: 0x2F3136
  owner_ids: [666581334637936640]
  initial_extensions: [
    "jishaku", "cogs.api", "cogs.events", "cogs.info",
    "cogs.level", "cogs.moderation", "cogs.owner", "cogs.utility",
  ]
  token: "ODU2NDUxMTA3ODM2Mzk1NTMw.Gmdzmd.mV4GjSy3s84butM_2l-TjPaN-1YIVq0uYZeJkY"

log:
  error_channel_id: 858679708363653120
  
reactionrole:
  max_role: 15

level:
  category_id: 854461755933196289